#!/bin/sh
export NIC=$(route -n | egrep "0.0.0.0" | awk '{print $8}' | sort -u) # With or not Gateway)
rede=$( dialog --stdout --inputbox 'Insert IPv6 (Format ->HHHH::):'    0 0 )
mask=$( dialog --stdout --inputbox 'Insert Prefix (ex. /n format):'    0 0 )
Quantity=$( dialog --stdout --inputbox 'Insert IPs Quantity (n):'    0 0 )

ifconfig $NIC down
ifconfig $NIC up

for conta in $(seq 1 $Quantity);
do
ifconfig $NIC add $rede$conta/$mask
done;

ifconfig > NIC 
dialog \
--title 'Ifconfig Show'  \
--textbox NIC \
0 0
rm NIC
